version: '3.7'

services:
  python-client:
    build:
      context: python/
    ports:
      - 8888:8888
    env_file: .env
  julia-client:
    build:
      context: julia/
    ports:
      - 8888:8888
    env_file: .env
  r-client:
    build:
      context: r/
    ports:
      - 8787:8787
    env_file: .env
