version: '3.7'

services:
  python-client:
    build:
      context: python/
    ports:
      - 8888:8888
    environment:
      - API_TOKEN
      - API_BASE_URL
  julia-client:
    build:
      context: julia/
    ports:
      - 8888:8888
    environment:
      - API_TOKEN
      - API_BASE_URL
  r-client:
    build:
      context: r/
    ports:
      - 8787:8787
    environment:
      - API_TOKEN
      - API_BASE_URL
